services:
  - type: web
    name: cwc23-flask
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
